name: iot_log_intelligence_pipeline
version: 1.0.0
config-version: 2

profile: analytics

model-paths:
  - models
seed-paths:
  - seeds
snapshot-paths:
  - snapshots
macro-paths:
  - macros
test-paths:
  - tests

clean-targets:
  - target
  - dbt_packages
  - logs

models:
  iot_log_intelligence_pipeline:
    +materialized: view
    staging:
      +materialized: table
    marts:
      +materialized: table
